import Head from "next/head";
import { Fragment } from "react";

import Post from "../../elements/Post/Post";

import styles from "./HomePage.module.css";

const HomePage = () => {
  return (
    <Fragment>
      <Head>
        <title>My Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.posts}>
          <Post isFullPost={false} />
          <Post isFullPost={false} />
          <Post isFullPost={false} />
          <Post isFullPost={false} />
        </div>
      </main>
    </Fragment>
  );
};

export default HomePage;
